version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: shopee-video-mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: shopee-video-gen
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - shopee-video-network

  # Note: Redis and RabbitMQ are now external services
  # - RabbitMQ: Using Koyeb endpoint (amqp://01.proxy.koyeb.app:21185)
  # - Redis: Not needed anymore (migrated to RabbitMQ)

  # Optional: MongoDB Admin UI
  mongo-express:
    image: mongo-express:latest
    container_name: shopee-video-mongo-express
    restart: unless-stopped
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb
    networks:
      - shopee-video-network
    profiles:
      - dev


volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local

networks:
  shopee-video-network:
    driver: bridge
