version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: shopee-video-mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: shopee-video-gen
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - shopee-video-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: shopee-video-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    networks:
      - shopee-video-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: shopee-video-rabbitmq
    restart: unless-stopped
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - shopee-video-network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shopee-video-backend
    restart: unless-stopped
    ports:
      - '3000:3000'
    env_file:
      - .env.docker
    volumes:
      - ./storage:/app/storage
      - ./assets:/app/assets
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - shopee-video-network
    profiles:
      - production

  # Optional: MongoDB Admin UI
  mongo-express:
    image: mongo-express:latest
    container_name: shopee-video-mongo-express
    restart: unless-stopped
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb
    networks:
      - shopee-video-network
    profiles:
      - dev

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
  rabbitmq_data:
    driver: local

networks:
  shopee-video-network:
    driver: bridge
