# Koyeb configuration
app: shopee-video-generator

services:
  - name: api-worker
    type: web
    env:
      # Runtime
      - name: NODE_ENV
        value: production
      - name: PORT
        value: "3000"
      - name: HOST
        value: 0.0.0.0

      # ⚠️  REQUIRED: Set these in Koyeb Dashboard > Secrets
      # Database
      # - name: MONGODB_URI
      #   secret: MONGODB_URI

      # AI API Key (choose one)
      # - name: OPENAI_API_KEY
      #   secret: OPENAI_API_KEY

      # Queue (Optional - will use synchronous mode if not available)
      - name: QUEUE_CONCURRENCY
        value: "3"

      # AI Configuration
      - name: AI_PROVIDER
        value: openai
      - name: OPENAI_MODEL
        value: gpt-4o-mini
      # ⚠️  Available models: gpt-4o, gpt-4o-mini, gpt-4-turbo

      - name: ANTHROPIC_MODEL
        value: claude-3-5-sonnet-20241022

      # Storage
      - name: STORAGE_PATH
        value: ./storage/videos
      - name: UPLOAD_PATH
        value: ./storage/uploads
      - name: MAX_FILE_SIZE
        value: "104857600"

      # Logging
      - name: LOG_LEVEL
        value: info

    build:
      dockerfile: Dockerfile

    ports:
      - port: 3000
        protocol: http

    regions:
      - fra

    instance_type: nano

    autoscaling:
      min: 1
      max: 1

    healthcheck:
      http:
        path: /health
        port: 3000
      grace_period: 30
      interval: 30
      timeout: 10
      restart_limit: 3
